/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Штатная проверка живости для балансера
         * @description Ручка userver, оставленная на месте (ADR-0013). Отвечает пустым телом:
         *     балансеру нужен код ответа, а не содержимое.
         *
         *     Тип содержимого у неё `application/octet-stream` — умолчание userver для
         *     ручки, которая его не назвала. Так и описано: спецификация говорит, что
         *     сервис делает, а не что нам хотелось бы. Своих ручек это не касается —
         *     они называют тип явно.
         *
         */
        get: operations["ping"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Процесс жив
         * @description Отвечает и тогда, когда база недоступна. Перезапускать процесс из-за
         *     упавшего хранилища — значит превратить сбой базы в отсутствие сервиса и
         *     потерять вместе с ним логи и метрики того, кто мог бы объяснить, что
         *     случилось. Готовность принимать трафик — соседняя ручка.
         *
         */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readiness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Готов принимать трафик
         * @description Готовность — это два условия сразу: база отвечает И схема не отстала от
         *     файлов. Процесс на отставшей схеме отвечает на запросы и молча делает не
         *     то: колонки, которой он ждёт, в базе ещё нет.
         *
         *     Ответ 503 здесь НЕ problem+json, и это единственное исключение во всём
         *     контуре. Оно названо и обосновано в docs/api/README.md: проба не
         *     отказывает в запросе, она отвечает на вопрос, а читает её оркестратор,
         *     который тела не разбирает вовсе.
         *
         */
        get: operations["readiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Спецификация как JSON
         * @description Тот же документ, что в docs/api/openapi.yaml, переведённый в JSON:
         *     инструменты порождения клиентов читают JSON, а человек — YAML. Второго
         *     источника правды не появляется — файл на диске один.
         *
         */
        get: operations["openapiDocument"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cabinet/{tenant}/sign-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Войти в кабинет
         * @description АРЕНДАТОР БЕРЁТСЯ ИЗ АДРЕСА КАБИНЕТА, а не из тела и не из cookie: почта
         *     уникальна ВНУТРИ арендатора, и «войти вообще» не выражается.
         *
         *     Сессия выдаётся заголовком `Set-Cookie` с атрибутами `HttpOnly`,
         *     `Secure`, `SameSite=Lax`, а не полем тела: `HttpOnly` ставится только
         *     заголовком, и положить сессию в тело значит попросить клиента самого
         *     сделать её недоступной скрипту, а он не сможет.
         *
         *     Неудачи НЕРАЗЛИЧИМЫ: нет такой записи, есть запись без пароля, пароль не
         *     подошёл — ответ один и тот же (`sign_in_refused`). Иначе форма входа
         *     превращается в способ узнать, кто у нас учится.
         *
         */
        post: operations["signIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Format: uuid
         * @example 018f2b3c-4d5e-4f60-8a71-b2c3d4e5f607
         */
        Uuid: string;
        /** @example 018f2b3c4d5e4f608a71b2c3d4e5f607 */
        RequestIdValue: string;
        /** @example {
         *       "alive": true
         *     } */
        Liveness: {
            /** @description Процесс отвечает. Про базу это не говорит ничего.
             *
             *     Всегда `true`, и записать это в схеме нечем: `const` порождение
             *     типов ломает (docs/api/README.md, «Чего спецификация себе не
             *     позволяет»). Обещание проверяет contract-набор, а не схема.
             *      */
            alive: boolean;
        };
        /** @example {
         *       "ready": false,
         *       "migrations": 0,
         *       "why": "схема пуста: миграции не применены"
         *     } */
        Readiness: {
            /** @description Можно ли давать трафик */
            ready: boolean;
            /** @description Сколько миграций применено. Отсутствует, когда база не ответила
             *     вовсе: посчитать было негде.
             *      */
            migrations?: number;
            /** @description Чего не хватает. Появляется только у неготовности. */
            why?: string;
        };
        /** @example {
         *       "email": "mail@example.org",
         *       "password": "correct-horse-battery"
         *     } */
        SignInRequest: {
            /** @description Почта. Уникальна ВНУТРИ арендатора, а не на площадке. */
            email: string;
            /** @description Пароль. `format: password` здесь НЕ СТОИТ намеренно: он не описывает
             *     значение, а просит показывалку спрятать ввод, — и порождение типов
             *     его не понимает (docs/api/README.md, «Чего спецификация себе не
             *     позволяет»).
             *      */
            password: string;
        };
        /** @example {
         *       "expires_at": 1780000000000000
         *     } */
        SignInAnswer: {
            /**
             * Format: int64
             * @description Когда сессия перестанет действовать: микросекунды от начала эпохи в
             *     UTC. Число, а не строка: у клиента и у сервера разные представления
             *     о том, как записать момент, а у числа их нет.
             *
             *     `format: int64` не украшение: без него порождённое поле сорокового
             *     года не вмещает, а микросекунды эпохи не вмещает уже сегодня.
             *
             */
            expires_at: number;
        };
        /**
         * @description ФОРМА ОТКАЗА ОДНА НА ВСЮ СИСТЕМУ — RFC 9457. Второй формы не заводят
         *     даже «на один случай»: разобрать пять форматов приходится всем, а чинить
         *     их — никому. Дублировать эту схему по ручкам тоже нельзя, и это не вкус:
         *     копия расходится с оригиналом в тот день, когда правку внесли в одну.
         *
         * @example {
         *       "type": "urn:pdr:error:request_field_invalid",
         *       "title": "Запрос не проходит схему",
         *       "status": 400,
         *       "detail": "поле «email» не проходит схему: слишком короткое",
         *       "instance": "/api/v1/cabinet/018f2b3c-4d5e-4f60-8a71-b2c3d4e5f607/sign-in",
         *       "request_id": "018f2b3c4d5e4f608a71b2c3d4e5f607",
         *       "field": "email"
         *     }
         */
        Problem: {
            type: components["schemas"]["ProblemType"];
            /** @description Короткое имя рода отказа. Одно на код, не зависит от обстоятельств. */
            title: string;
            status: number;
            /** @description Что случилось в этот раз — человеку и в журнал. Клиент разбирает
             *     `type`, а не эту строку: она меняется без предупреждения.
             *      */
            detail: string;
            /** @description Путь запроса, на котором отказали. */
            instance: string;
            request_id: components["schemas"]["RequestIdValue"];
            /** @description Поле, из-за которого отказ, — путь внутри тела запроса. Появляется
             *     только у отказа разбора: «bad request» без имени поля отправляет
             *     человека угадывать, а разработчика — читать схему глазами.
             *      */
            field?: string;
        };
        /**
         * @description ОПОЗНАВАТЕЛЬ РОДА ОТКАЗА, ПЕРЕЧИСЛЕНИЕМ, а не свободной строкой. Клиент
         *     сравнивает `type` с константой, и константа обязана быть в контракте:
         *     иначе он сравнивает строки, которые мы переименовываем не спросив.
         *
         *     URN, а не ссылка: страницы с описанием у нас нет, а `type`, ведущий в
         *     никуда, — обещание, которого мы не выполняем.
         *
         *     Список пополняется без смены версии — новый род отказа старый клиент
         *     просто не узнает и покажет `title`. УДАЛЕНИЕ значения ломающее:
         *     docs/api/README.md.
         *
         *     В списке только то, что клиент может увидеть. Коды проверки внутренних
         *     настроек сюда не входят: их человек не видит вовсе
         *     (docs/product/voice.md, «Коды, которых человек не увидит»). Что сегодня
         *     сломанный динамический конфиг всё-таки выпускает такой код наружу —
         *     названо в docs/api/README.md как расхождение, а не узаконено здесь.
         *
         * @example urn:pdr:error:sign_in_refused
         * @enum {string}
         */
        ProblemType: "urn:pdr:error:request_not_json" | "urn:pdr:error:request_field_invalid" | "urn:pdr:error:idempotency_key_required" | "urn:pdr:error:idempotency_key_in_flight" | "urn:pdr:error:idempotency_key_reused" | "urn:pdr:error:cabinet_unknown" | "urn:pdr:error:sign_in_refused" | "urn:pdr:error:sign_in_throttled";
    };
    responses: {
        /** @description Запрос не разобрался или не хватает обязательного заголовка */
        Malformed: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Кто вы. 401 говорит клиенту войти заново, 403 — что входить бесполезно;
         *     родом доменной ошибки это не выражается, поэтому шаг опознания отвечает
         *     отдельно.
         *      */
        Unidentified: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Состояние не позволяет выполнить сейчас */
        Conflict: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Данные не проходят правило домена */
        Refused: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Срок, отведённый КЛИЕНТОМ (`X-YaTaxi-Client-TimeoutMs`), истёк раньше, чем
         *     до запроса дошли. Работа не начиналась: ни транзакции, ни занятого ключа
         *     повтора после этого ответа не остаётся — тот же ключ можно прислать
         *     снова, и он сработает как первый.
         *
         *     498, а не 504, и разница не в номере. 504 означает «мы кого-то ждали и не
         *     дождались» — наша неудача, повтор осмыслен. 498 означает «времени не было
         *     с самого начала»: повторять то же самое с тем же сроком незачем, надо
         *     дать срок больше.
         *
         *     ЭТОТ ОТВЕТ НЕ problem+json, и это ВТОРОЕ названное исключение во всём
         *     контуре (первое — 503 у `/readiness`). Отвечает не наша форма, а штатный
         *     механизм доведения срока: он обрывает запрос ДО хендлера, и потому ни
         *     одного нашего заголовка и ни одной нашей строки в ответе нет.
         *
         *     БОЛЬШЕ ТОГО: тип содержимого здесь НЕ СХОДИТСЯ С ТЕЛОМ. Приходит
         *     `application/json`, а телом лежит обычный текст «Deadline expired». Это
         *     дефект штатного механизма, и описан он тут как есть — спецификация
         *     говорит, что сервис делает, а не что нам хотелось бы.
         *
         *     Отсюда правило для клиента: НА 498 ТЕЛО НЕ РАЗБИРАЮТ. Всё, что нужно
         *     знать, — в самом коде: срок вышел, работа не начиналась, повторять надо с
         *     большим сроком.
         *
         *     Своей формой это не переписать, не написав свой базовый хендлер, — а он
         *     запрещён (ADR-0013).
         *      */
        Expired: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /** @example Deadline expired */
                "application/json": string;
            };
        };
        /** @description Поломка на нашей стороне */
        Broken: {
            headers: {
                "X-Request-Id": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description Кабинет, в который входят. Идентификатор арендатора. */
        Tenant: components["schemas"]["Uuid"];
        /**
         * @description ОБЯЗАТЕЛЕН НА КАЖДОМ МЕНЯЮЩЕМ ОБРАЩЕНИИ, и это не пожелание: без него
         *     повтор по оборванной связи выполняет операцию второй раз. Клиент
         *     придумывает ключ сам и повторяет запрос С ТЕМ ЖЕ ключом; в течение срока
         *     жизни ключа (динамическое значение `PDR_IDEMPOTENCY`) он получает
         *     сохранённый ответ, а не второе выполнение.
         *
         *     Тот же ключ с ДРУГИМ телом — ошибка клиента, а не повтор:
         *     `idempotency_key_reused`.
         *
         * @example sign-in-7f3c1a94-6d0b-4f2e-9c31-8a5b0e2d4c77
         */
        IdempotencyKey: string;
        /**
         * @description СКОЛЬКО МИЛЛИСЕКУНД КЛИЕНТ ГОТОВ ЖДАТЬ. Не пожелание: по этому сроку
         *     сервис обрывает работу, которую клиент всё равно уже не примет, и не даёт
         *     очереди такой работы добить себя под перегрузкой.
         *
         *     Остаток времени доходит до запросов к базе сам — доведение срока
         *     (`USERVER_DEADLINE_PROPAGATION_ENABLED`) включено. Срок, истёкший до того,
         *     как до запроса дошли, — это `498`, и работа не начинается вовсе.
         *
         *     Имя заголовка не наше: так его называет штатный механизм userver, и
         *     переименовать его значило бы написать свой (ADR-0013).
         *
         * @example 5000
         */
        ClientTimeout: number;
        /** @description След запроса. Свой годный принимается и возвращается нетронутым, иначе
         *     сервис заводит собственный. Он же приходит в ответе и в теле отказа:
         *     жалобу «у меня не работает» разбирают по нему, а человек может назвать
         *     только то, что видел сам.
         *      */
        RequestId: components["schemas"]["RequestIdValue"];
    };
    requestBodies: never;
    headers: {
        /** @description След запроса — тот же, что в теле отказа. */
        RequestId: components["schemas"]["RequestIdValue"];
        /** @description Стоит только на ПОВТОРЕ: ответ взят из сохранённого, операция второй раз
         *     не выполнялась.
         *      */
        IdempotencyReplayed: string;
        /**
         * @description Сессия. Имя `__Host-pdr_session` — не стиль, а требование браузера:
         *     cookie с такой приставкой принимается только с `Secure`, только с
         *     корневого пути и только без `Domain`, поэтому поддомен одного арендатора
         *     не может подсунуть свою cookie другому.
         *
         *     НА ПОВТОРЕ ЗАГОЛОВКА НЕТ, и это не упущение: повтор отдаёт сохранённые
         *     тело и код, а сессия у клиента уже есть с первого раза. Повтор узнаётся
         *     по `Idempotency-Replayed`.
         *
         * @example __Host-pdr_session=...; HttpOnly; Secure; SameSite=Lax; Path=/
         */
        SetSessionCookie: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ping: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Процесс отвечает */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            /** @description Компонент в неисправном состоянии */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Процесс жив */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Liveness"];
                };
            };
        };
    };
    readiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description База отвечает, миграции применены */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
            /** @description База недоступна или схема пуста */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
        };
    };
    openapiDocument: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Спецификация */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    signIn: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description ОБЯЗАТЕЛЕН НА КАЖДОМ МЕНЯЮЩЕМ ОБРАЩЕНИИ, и это не пожелание: без него
                 *     повтор по оборванной связи выполняет операцию второй раз. Клиент
                 *     придумывает ключ сам и повторяет запрос С ТЕМ ЖЕ ключом; в течение срока
                 *     жизни ключа (динамическое значение `PDR_IDEMPOTENCY`) он получает
                 *     сохранённый ответ, а не второе выполнение.
                 *
                 *     Тот же ключ с ДРУГИМ телом — ошибка клиента, а не повтор:
                 *     `idempotency_key_reused`.
                 *
                 * @example sign-in-7f3c1a94-6d0b-4f2e-9c31-8a5b0e2d4c77
                 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description След запроса. Свой годный принимается и возвращается нетронутым, иначе
                 *     сервис заводит собственный. Он же приходит в ответе и в теле отказа:
                 *     жалобу «у меня не работает» разбирают по нему, а человек может назвать
                 *     только то, что видел сам.
                 *      */
                "X-Request-Id"?: components["parameters"]["RequestId"];
                /**
                 * @description СКОЛЬКО МИЛЛИСЕКУНД КЛИЕНТ ГОТОВ ЖДАТЬ. Не пожелание: по этому сроку
                 *     сервис обрывает работу, которую клиент всё равно уже не примет, и не даёт
                 *     очереди такой работы добить себя под перегрузкой.
                 *
                 *     Остаток времени доходит до запросов к базе сам — доведение срока
                 *     (`USERVER_DEADLINE_PROPAGATION_ENABLED`) включено. Срок, истёкший до того,
                 *     как до запроса дошли, — это `498`, и работа не начинается вовсе.
                 *
                 *     Имя заголовка не наше: так его называет штатный механизм userver, и
                 *     переименовать его значило бы написать свой (ADR-0013).
                 *
                 * @example 5000
                 */
                "X-YaTaxi-Client-TimeoutMs"?: components["parameters"]["ClientTimeout"];
            };
            path: {
                /** @description Кабинет, в который входят. Идентификатор арендатора. */
                tenant: components["parameters"]["Tenant"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignInRequest"];
            };
        };
        responses: {
            /** @description Вошли, сессия выдана в cookie */
            200: {
                headers: {
                    "Set-Cookie": components["headers"]["SetSessionCookie"];
                    "X-Request-Id": components["headers"]["RequestId"];
                    "Idempotency-Replayed": components["headers"]["IdempotencyReplayed"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignInAnswer"];
                };
            };
            400: components["responses"]["Malformed"];
            401: components["responses"]["Unidentified"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Refused"];
            498: components["responses"]["Expired"];
            500: components["responses"]["Broken"];
        };
    };
}
